spring.application.name=one
spring.profiles.active=dev
spring.datasource.url=jdbc:mysql://localhost:3306/one?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root


spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration